/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.cloud.drive.bean;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

/**
 * Definition of ObjectType MemoInfo.
 *
 * @since 2023-12-10
 */
@PrimaryKeys({"id"})
public final class MemoInfo extends CloudDBZoneObject {
    private Long id;

    private String title;

    private String content;

    public MemoInfo() {
        super(MemoInfo.class);
    }
    public MemoInfo(Long id, String title, String content){
        super(MemoInfo.class);
        this.id = id;
        this.title = title;
        this.content = content;
    }
    public void setId(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getTitle() {
        return title;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getContent() {
        return content;
    }

}
